export const offersDetails = {
  securisation: {
    key: "SECURISATION",
    slug: "controle-eaje",
    title: "Contrôle EAJE",
    subtitle: "Pack Contrôle EAJE - Sécurisation réglementaire",
    process: [
      "Phase 1 : Cadrage initial (1 journée) - Analyse de votre situation actuelle et identification des besoins prioritaires",
      "Phase 2 : Audit express - Évaluation rapide de la conformité réglementaire de votre structure",
      "Phase 3 : Mise en conformité - Accompagnement dans la mise à jour des dossiers et processus",
      "Phase 4 : Appropriation - Formation de votre équipe aux outils et procédures",
      "Phase 5 : Suivi et ajustements - Points réguliers pour garantir la pérennité de la conformité",
    ],
    objectives: [
      "Mettre en conformité tous les dossiers réglementaires de la structure",
      "Sécuriser les processus et procédures d'accueil",
      "Disposer d'outils pratiques et opérationnels (check-lists, modèles de documents)",
      "Former l'équipe à l'utilisation des outils de contrôle",
      "Garantir la traçabilité et la conformité continue",
    ],
    method: [
      "Accompagnement personnalisé adapté à votre contexte et à vos contraintes",
      "Outils pratiques directement utilisables (templates, check-lists, guides)",
      "Formation de l'équipe pour une appropriation durable",
      "Espace client sécurisé avec accès à tous les documents et outils",
      "Support régulier par messagerie et rendez-vous de suivi",
    ],
    utility: [
      "Réduire les risques de non-conformité lors des contrôles",
      "Gagner du temps dans la gestion administrative quotidienne",
      "Rassurer les familles et les partenaires institutionnels",
      "Faciliter la transmission des informations entre équipes",
      "Disposer d'une base solide pour évoluer vers d'autres offres d'accompagnement",
    ],
    regulatoryPoints: [
      "Conformité aux normes d'accueil du jeune enfant (décret n°2021-1131)",
      "Dossiers d'admission complets et à jour",
      "Projet d'établissement conforme",
      "Documentation des pratiques professionnelles",
      "Respect des ratios d'encadrement",
      "Sécurité des locaux et équipements",
      "Hygiène et santé (protocoles, PAI, etc.)",
      "Traçabilité des activités et des incidents",
    ],
    price: 1500,
  },
  structuration: {
    key: "STRUCTURATION",
    slug: "organisation-pratiques",
    title: "Organisation & Pratiques",
    subtitle: "Structuration de votre établissement",
    process: [
      "Phase 1 : Cadrage approfondi (2 journées) - Analyse complète de l'organisation actuelle et définition des objectifs",
      "Phase 2 : Parcours d'entrée - Mise en place d'un processus structuré d'accueil des enfants et familles",
      "Phase 3 : Chrono-Manager - Organisation et planification des tâches de direction",
      "Phase 4 : Box Besoins - Identification et réponse aux besoins spécifiques de votre structure",
      "Phase 5 : Accompagnement dans la durée - Suivi régulier et ajustements sur 6 à 12 mois",
    ],
    objectives: [
      "Structurer l'organisation interne de la structure",
      "Améliorer les pratiques d'accueil et d'accompagnement",
      "Optimiser la gestion quotidienne et la planification",
      "Renforcer la cohérence des pratiques entre équipes",
      "Développer l'autonomie de la structure dans sa gestion",
    ],
    method: [
      "Diagnostic approfondi de votre organisation actuelle",
      "Création d'outils sur-mesure adaptés à votre contexte",
      "Formation et accompagnement des équipes",
      "Mise en place de processus structurés et documentés",
      "Suivi régulier avec ajustements et améliorations continues",
    ],
    utility: [
      "Améliorer la qualité d'accueil des enfants et familles",
      "Réduire le stress et la charge de travail des équipes",
      "Optimiser l'organisation et gagner en efficacité",
      "Renforcer la cohésion d'équipe",
      "Disposer d'outils pérennes pour une gestion autonome",
    ],
    regulatoryPoints: [
      "Respect des obligations d'accueil et d'accompagnement",
      "Documentation des pratiques professionnelles",
      "Traçabilité des parcours d'entrée",
      "Gestion des besoins spécifiques (handicap, santé, etc.)",
      "Communication avec les familles",
      "Organisation des temps d'activité",
      "Gestion des ressources humaines",
    ],
    price: 3000,
  },
  pilotageQualite: {
    key: "PILOTAGE_QUALITE",
    slug: "accompagnement-premium",
    title: "Accompagnement Premium",
    subtitle: "Pilotage Qualité complet",
    process: [
      "Phase 1 : Cadrage stratégique (3 journées) - Analyse approfondie et définition du plan d'actions personnalisé",
      "Phase 2 : Échelle Qualité EAJE - Auto-diagnostic et évaluation de votre structure sur 5 niveaux",
      "Phase 3 : Plan d'actions - Définition et mise en œuvre d'un plan d'amélioration continue",
      "Phase 4 : Accompagnement régulier - Suivi mensuel avec ajustements et optimisations",
      "Phase 5 : Autonomie - Transfert de compétences pour un pilotage autonome de la qualité",
    ],
    objectives: [
      "Piloter la qualité de manière continue et structurée",
      "Développer une culture qualité au sein de la structure",
      "Mettre en place un système d'évaluation et d'amélioration continue",
      "Renforcer la satisfaction des familles et des équipes",
      "Atteindre l'autonomie dans le pilotage qualité",
    ],
    method: [
      "Utilisation de l'Échelle Qualité EAJE comme outil de référence",
      "Accompagnement personnalisé et adaptatif selon vos besoins",
      "Mise en place d'indicateurs de suivi et de tableaux de bord",
      "Formation approfondie des équipes aux outils et méthodes",
      "Suivi régulier avec analyse des résultats et ajustements",
    ],
    utility: [
      "Disposer d'une vision claire de la qualité de votre structure",
      "Identifier les axes d'amélioration prioritaires",
      "Mettre en place une démarche d'amélioration continue",
      "Renforcer la satisfaction et la fidélisation des familles",
      "Valoriser votre structure auprès des partenaires institutionnels",
    ],
    regulatoryPoints: [
      "Conformité réglementaire complète et maintenue",
      "Respect des normes qualité d'accueil",
      "Documentation complète des pratiques et processus",
      "Traçabilité exhaustive des activités et résultats",
      "Évaluation et amélioration continue",
      "Gestion des risques et prévention",
      "Communication et transparence avec les parties prenantes",
    ],
    price: 6000,
  },
};
